<a href="https://colab.research.google.com/github/MathewNhari/Sendy-Logistics-Challenge/blob/master/Sendy_Logistics_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import Libaries**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Import Data

In [2]:

riders = pd.read_csv('Riders.csv')
SampleSubmission = pd.read_csv('SampleSubmission.csv')
Test_df = pd.read_csv('Test.csv')
Train_df = pd.read_csv('Train.csv')
VariableDefinitions = pd.read_csv('VariableDefinitions.csv')

**Variable Definations**

In [3]:
VariableDefinitions

Order No                Unique number identifying the order
0                                     User Id  Unique number identifying the customer on a pl...
1                                Vehicle Type  For this competition limited to bikes, however...
2                               Platform Type  Platform used to place the order, there are 4 ...
3                        Personal or Business                                      Customer type
4                    Placement - Day of Month                  Placement - Day of Month i.e 1-31
5                Placement - Weekday (Mo = 1)                   Placement - Weekday (Monday = 1)
6                            Placement - Time  Placement - Time - Time of day the order was p...
7                 Confirmation - Day of Month               Confirmation - Day of Month i.e 1-31
8             Confirmation - Weekday (Mo = 1)                Confirmation - Weekday (Monday = 1)
9                         Confirmation - Time  Confirmation - Time - Time of day the order wa...
10           Arrival at Pickup - Day of Month          Arrival at Pickup - Day of Month i.e 1-31
11       Arrival at Pickup - Weekday (Mo = 1)           Arrival at Pickup - Weekday (Monday = 1)
12                   Arrival at Pickup - Time  Time of day the the rider arrived at the locat...
13                      Pickup - Day of Month                     Pickup - Day of Month i.e 1-31
14                  Pickup - Weekday (Mo = 1)                      Pickup - Weekday (Monday = 1)
15                              Pickup - Time  Pickup - Time - Time of day the the rider pick...
16      Arrival at Destination - Day of Month        Arrival at Delivery - Day of Month i.e 1-31
17  Arrival at Destination - Weekday (Mo = 1)         Arrival at Delivery - Weekday (Monday = 1)
18              Arrival at Destination - Time  Arrival at Delivery Time - Time of day the rid...
19                              Distance (KM)            The distance from Pickup to Destination
20                                Temperature  Temperature at the time of order placement in ...
21               Precipitation in millimeters   Precipitation at the time of order placement ...
22                                 Pickup Lat                       Latitude of pick up location
23                                Pickup Long                      Longitude of pick up location
24                            Destination Lat                      Latitude of delivery location
25                           Destination Long                     Longitude of delivery location
26                                   Rider Id             ID of the Rider who accepted the order
27                Time from Pickup to Arrival  Time in seconds between 'Pickup' and 'Arrival ...
28                                        NaN                                                NaN
29                              Rider Metrics                                                NaN
30                                   Rider Id  Unique number identifying the rider (same as i...
31                               No_Of_Orders           Number of Orders the rider has delivered
32                                        Age  Number of days since the rider delivered the f...
33                             Average_Rating                        Average rating of the rider
34                              No_of_Ratings   Number of ratings the rider has received. Rat...

**Sample Submission**

In [4]:
SampleSubmission.head()

Order_No  Time from Pickup to Arrival
0  Order_No_19248                        567.0
1  Order_No_12736                       4903.0
2    Order_No_768                       5649.0
3  Order_No_15332                          NaN
4  Order_No_21373                          NaN

**Data**

In [5]:
riders.head()

Rider Id  No_Of_Orders   Age  Average_Rating  No_of_Ratings
0  Rider_Id_396          2946  2298            14.0           1159
1  Rider_Id_479           360   951            13.5            176
2  Rider_Id_648          1746   821            14.3            466
3  Rider_Id_753           314   980            12.5             75
4  Rider_Id_335           536  1113            13.7            156

In [6]:
Test_df.head()

Order No       User Id  ... Destination Long      Rider Id
0  Order_No_19248  User_Id_3355  ...        36.822390  Rider_Id_192
1  Order_No_12736  User_Id_3647  ...        36.823907  Rider_Id_868
2    Order_No_768  User_Id_2154  ...        36.851365   Rider_Id_26
3  Order_No_15332  User_Id_2910  ...        36.790658  Rider_Id_685
4  Order_No_21373  User_Id_1205  ...        36.792161  Rider_Id_858

[5 rows x 25 columns]

In [7]:
Train_df.head()

Order No       User Id  ...      Rider Id  Time from Pickup to Arrival
0   Order_No_4211   User_Id_633  ...  Rider_Id_432                          745
1  Order_No_25375  User_Id_2285  ...  Rider_Id_856                         1993
2   Order_No_1899   User_Id_265  ...  Rider_Id_155                          455
3   Order_No_9336  User_Id_1402  ...  Rider_Id_855                         1341
4  Order_No_27883  User_Id_1737  ...  Rider_Id_770                         1214

[5 rows x 29 columns]

Joining the Test_df and Train_df to riders 

In [8]:
Test = Test_df.merge(riders,on='Rider Id',how='inner')
Train = Train_df.merge(riders,on='Rider Id',how='inner')

In [9]:
Train.head()

Order No       User Id  ... Average_Rating  No_of_Ratings
0   Order_No_4211   User_Id_633  ...           13.8            549
1  Order_No_27440  User_Id_2642  ...           13.8            549
2  Order_No_14170  User_Id_3339  ...           13.8            549
3  Order_No_21727  User_Id_3523  ...           13.8            549
4   Order_No_8301    User_Id_87  ...           13.8            549

[5 rows x 33 columns]

In [10]:
#if no output is returned, the columns are equal otherwise returns 'Not True' as Assertion Error.
#input the column names manually
#checking if months columns are equal then checking the weekdays
assert Train['Pickup - Day of Month'].all() == Train['Arrival at Destination - Day of Month'].all(), "Not True"

# **Cleaning Data**


Checking for Duplicates

In [11]:
#No duplicate Data On Test Data
def Check_duplicates(df):
  duplicates = df.duplicated(subset = ['Order No'], keep = False)
  return df[duplicates]

Checking Duplicates on Train Data

In [12]:
#No duplicates 
Train_duplicates = Check_duplicates(Train)
Test_duplucates = Check_duplicates(Test)

Drop Columns

In [13]:
def columnDrop(df,columns):
  df.drop(columns, axis=1,inplace=True)
  return df

In [14]:
Drop_Train_Cols = ['Vehicle Type', 'Order No', 'User Id', 'Rider Id', 'Placement - Day of Month', 'Placement - Weekday (Mo = 1)',
       'Confirmation - Day of Month', 'Confirmation - Weekday (Mo = 1)', 'Arrival at Pickup - Day of Month',
       'Arrival at Pickup - Weekday (Mo = 1)', 'Arrival at Destination - Day of Month',
       'Arrival at Destination - Weekday (Mo = 1)', 'Arrival at Destination - Time', 'Precipitation in millimeters']
Drop_Test_Cols = ['Vehicle Type', 'Order No', 'User Id', 'Rider Id', 'Placement - Day of Month', 'Placement - Weekday (Mo = 1)',
       'Confirmation - Day of Month', 'Confirmation - Weekday (Mo = 1)','Precipitation in millimeters']
       
Test= columnDrop(Test,Drop_Test_Cols)
Train = columnDrop(Train,Drop_Train_Cols)

**Changing  into The Correct DataType**

In [15]:
 category_cols = ['Platform Type', 'Pickup - Day of Month', 'Pickup - Weekday (Mo = 1)', 'Personal or Business']
       
Train[category_cols] = Train[category_cols].astype('category')
Test[category_cols] = Test[category_cols].astype('category')


Setting Time columns into datetime Data type


In [16]:
def timeconvert(df,Time_Cols):
  for item in Time_Cols:
    df[item] = (pd.to_datetime(df[item].str.strip(), format='%I:%M:%S %p').dt.strftime('%H:%M:%S'))
  df[Time_Cols] = df[Time_Cols].astype('datetime64')
  return df
    

In [17]:
#Getting all time columns into a list
Cols = ['Placement - Time','Confirmation - Time','Pickup - Time']
#Train_Cols = ['Placement - Time', 'Confirmation - Time', 'Arrival at Pickup - Time', 'Pickup - Time']

Train = timeconvert(Train,Cols)
Test = timeconvert(Test,Cols)


In [18]:
Train.head()

Platform Type Personal or Business  ... Average_Rating No_of_Ratings
0             3             Business  ...           13.8           549
1             3             Personal  ...           13.8           549
2             3             Business  ...           13.8           549
3             3             Personal  ...           13.8           549
4             2             Personal  ...           13.8           549

[5 rows x 19 columns]

In [19]:
Train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21201 entries, 0 to 21200
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype         
---  ------                       --------------  -----         
 0   Platform Type                21201 non-null  category      
 1   Personal or Business         21201 non-null  category      
 2   Placement - Time             21201 non-null  datetime64[ns]
 3   Confirmation - Time          21201 non-null  datetime64[ns]
 4   Arrival at Pickup - Time     21201 non-null  object        
 5   Pickup - Day of Month        21201 non-null  category      
 6   Pickup - Weekday (Mo = 1)    21201 non-null  category      
 7   Pickup - Time                21201 non-null  datetime64[ns]
 8   Distance (KM)                21201 non-null  int64         
 9   Temperature                  16835 non-null  float64       
 10  Pickup Lat                   21201 non-null  float64       
 11  Pickup Long                  21201 non-nu

# **PreProcessing**

**Taking Care of Missing Data**

In [20]:
from sklearn.impute import SimpleImputer

def missingData(df,columns):
  imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
  imputer.fit(df[columns])
  df[columns] = imputer.transform(df[columns])
  return df

In [21]:
columns = ['Temperature']
Test = missingData(Test,columns)
Train = missingData(Train,columns)

Getting our Training Data into Features and Response variables

In [22]:
X = Train.drop(['Time from Pickup to Arrival'], axis=1)
y = Train[['Time from Pickup to Arrival']]

Encoding Categorical Variables

In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#lst = [0,1,2,3,5,6,8,9,11,12,14,15]
ct = ColumnTransformer(transformers =[('encoder' , OneHotEncoder(), category_cols)], remainder ='passthrough')
X = np.array(ct.fit_transform(X))

In [24]:
print(X)

[[0.0 0.0 1.0 ... 1309 13.8 549]
 [0.0 0.0 1.0 ... 1309 13.8 549]
 [0.0 0.0 1.0 ... 1309 13.8 549]
 ...
 [0.0 0.0 1.0 ... 105 0.0 0]
 [0.0 0.0 1.0 ... 448 15.0 2]
 [0.0 0.0 1.0 ... 1109 13.7 73]]
